
package pl.altkom.shop.wsclient.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductSOAPWebService", targetNamespace = "http://cxf.shop.altkom.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductSOAPWebService {


    /**
     * 
     * @param id
     * @return
     *     returns pl.altkom.shop.wsclient.soap.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://cxf.shop.altkom.pl/", className = "pl.altkom.shop.wsclient.soap.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://cxf.shop.altkom.pl/", className = "pl.altkom.shop.wsclient.soap.FindByIdResponse")
    public Product findById(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
